In [ ]:
import torch

# 1. 张量基础
print(f"PyTorch 版本: {torch.__version__}")

# 标量（0维张量）
scale = torch.tensor(7)
print(f"标量: {scale}, ndim: {scale.ndim}")

# 向量（1维张量）
vector = torch.tensor([7, 7, 8], dtype=torch.float64)
print(f"向量: {vector}, shape: {vector.shape}, dtype: {vector.dtype}")

# 随机张量
random_tensor = torch.rand(size=(2, 3))
print(f"随机张量:\n{random_tensor}, dtype: {random_tensor.dtype}")

In [ ]:
# 2. MPS 设备（Mac GPU 加速）
some_tensor = torch.rand(3, 4, device="mps")

print(f"张量:\n{some_tensor}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

In [ ]:
scale.item()  # 标量取值

In [ ]:
vector.shape, vector.dtype

In [ ]:
random_tensor, random_tensor.dtype

In [ ]:
some_tensor.shape

In [ ]:
# 3. 基础运算
tensor = torch.tensor([1, 2, 3])
print(f"加法: {tensor + 10}")
print(f"乘法: {tensor * 10}")
print(f"元素积: {tensor * tensor}")

In [ ]:
# 4. 矩阵乘法
# 两种写法等价：torch.matmul(a, b) 和 a @ b
print(f"点积: {torch.matmul(tensor, tensor)}")
print(f"@ 运算符: {tensor @ tensor}")

# 2x3 @ 3x2 -> 2x2
matrix = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
print(f"矩阵乘法:\n{matrix @ matrix.T}")

In [ ]:
tensor @ tensor  # 矩阵乘法简写

In [ ]:
# 2x3 矩阵乘转置 -> 2x2
tensor = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
print(f"矩阵乘转置:\n{tensor @ tensor.T}")

In [ ]:
# 删除重复内容

In [ ]:
# 删除重复内容

In [ ]:
# 5. 线性层（神经网络基础）
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
torch.manual_seed(42)

# Linear(in_features=2, out_features=10) -> 2维输入，10维输出
linear = torch.nn.Linear(in_features=2, out_features=10)
output = linear(tensor_A)

print(f"输入: {tensor_A.shape} -> 输出: {output.shape}")
print(f"权重: {linear.weight.shape}")

In [4]:
import torch
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [6]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [7]:
x.argmax()

tensor(9)

In [8]:
x.argmin()

tensor(0)

In [9]:
x.argsort(
)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [14]:
tensor_float = tensor.type(torch.float16)
tensor_float

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [18]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [26]:
x_reshape = x.reshape(2, 4)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [17]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))